# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewDialog(object):
    def setupUi(self, NewDialog):
        NewDialog.setObjectName("NewDialog")
        NewDialog.resize(796, 337)
        self.pushButton = QtWidgets.QPushButton(NewDialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(NewDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 100, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(NewDialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 130, 741, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(NewDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(NewDialog)
        self.spinBox.setGeometry(QtCore.QRect(20, 30, 101, 31))
        self.spinBox.setObjectName("spinBox")

        self.retranslateUi(NewDialog)
        QtCore.QMetaObject.connectSlotsByName(NewDialog)

    def retranslateUi(self, NewDialog):
        _translate = QtCore.QCoreApplication.translate
        NewDialog.setWindowTitle(_translate("NewDialog", "Изменение базы данных"))
        self.pushButton.setText(_translate("NewDialog", "Добавить"))
        self.pushButton_2.setText(_translate("NewDialog", "Загрузить"))
        self.label.setText(_translate("NewDialog", "ID:"))
